### ISSUE TITLE
Dark edges on the Moon

### ISSUE THREAD

**Issue by MJacred** [Lexpartizan/Godot_sky_shader#1]
I opened the project in version 3.1.2.stable.mono on Ubuntu 18.04, but Player.tscn is corrupted: "unexpected end of file".  
This is probably due to version mismatch of Godot...

**Comment by Lexpartizan** [comment]
I use 3.2 version.
Yes for 3.1 there is such an error.
Tomorrow I will try to assemble the scene from scratch in 3.1.2
There shouldn’t be anything in the shader that depends on the version.

**Comment by MJacred** [comment]
Thanks for the info!

I assume you use GLES3?

I got for newest commit from master branch the following error in Sky.shader while using GLES3:
```GLSL
 :28 - Expected function, uniform or varying 
 drivers/gles3/rasterizer_storage_gles3.cpp:2158 - Condition ' err != OK ' is true.
```

for GLES2 I got

```GLSL
 drivers/gles2/shader_gles2.cpp:129 - SceneShaderGLES2: Fragment shader compilation failed:
0(934) : error C7532: global function inverse requires "#version 140" or later
0(934) : error C0000: ... or #extension GL_ARB_gpu_shader5 : enable

 drivers/gles2/shader_gles2.cpp:364 - Method/Function Failed, returning: __null
 drivers/gles2/shader_gles2.cpp:88 - Condition ' !version ' is true. returned: false
 drivers/gles2/shader_gles2.h:254 - Condition ' !version ' is true. returned: -1
```

**Comment by Lexpartizan** [comment]
GLES 3.
i slighty rewrite shader for 3.1 becouse 3.1 dont support const and switch and make simple scene with camera (uncontrollable).
https://github.com/Lexpartizan/Godot_sky_shader/blob/master/Godot_sky_shader_for_3_1_2.zip

**Comment by MJacred** [comment]
Thanks! It works. Now it only shows a warning
```HLSL
The class variable 'lighting_stength' is declared but never used in the script.
  <Source>       Sky.tscn::1:14
```

I guess it's re-declared in line 28 `var lighting_stength = clamp(sin(iTime*31.4),0.1,1.0)`

I tested and checked the results against your video from 8 Jan 2020 and I noticed some artefacts only in my local build at the cloud edges, but only when day_time set to what I chose (see image below).  
**Do you have the same issue in your latest build (either when using Godot 3.1.2. or 3.2)?**  
When the sun is showing, I see flickering at the cloud edges (night time at the right end of the day_time slider seems to cause the artefacts -> based on the flickering, I reckon)

![sky-artefacts](https://user-images.githubusercontent.com/6639237/73599080-c8107780-453f-11ea-9b4f-bbc816dc94ba.png)

**Comment by Lexpartizan** [comment]
**lighting_stength:**
yes, you can delete line 14, this mistake. Thanks, i fix it.

**cloud edges on the moon:**
They were from the beginning. I don't know how to remove them. This is due to the fact that I draw the moon where there are no clouds. If you draw the moon completely and apply clouds, the Moon will shine through the clouds, as the Sun does.I chose the dark edges from two evils.

**Comment by Lexpartizan** [comment]
i can fix dark edges, wait.

**Comment by Lexpartizan** [comment]
I fix dark edges.

**Comment by MJacred** [comment]
Thank you very much again, the dark edges are gone!

The alpha clamping worked well.

Side note:  
Maybe a second repository for compatibility with versions before Godot 3.2 would be beneficial, as version 3.1.* will receive long-term support.  
Then you can use const and switch again (ie. your `switch (int(DAY_TIME.x))`).

**Comment by Lexpartizan** [comment]
i just leave shader version for 3.1)) This work and for 3.2.
And zip simple scene for 3.1.

**Comment by MJacred** [comment]
Sorry, I'm not sure I understood you correctly.  
Did you mean that you will leave the shader as it is, because it works for both Godot versions?

If you meant this: Should not the switch-statement improve the performance for Godot 3.2? Right now, it checks the statements in all if-clauses, even though only one can be true. In a switch-clause the code can make an early exit and skip the other checks

**Comment by Lexpartizan** [comment]
**Did you mean that you will leave the shader as it is, because it works for both Godot versions?**
Yes
I'm not sure what the switch is really improve perfomance. If need it you can edited shader.
Maybe later made two versions, but now i'm lazy))

**Comment by MJacred** [comment]
Alright, thank you. Will try to do performance test when I switch to Godot 3.2

Will close issue!

**Comment by Lexpartizan** [comment]
Not at all)) You made this sky better with this issue!

**Comment by MJacred** [comment]
together (•̀ᴗ•́)و ̑̑

**Comment by Lexpartizan** [comment]
Yes!
