### ISSUE TITLE
God Ray support

### ISSUE THREAD

**Issue by MJacred** [Lexpartizan/Godot_sky_shader#3]
You can use https://github.com/SIsilicon/Godot-God-Rays-Plugin for inspiration or collaborate with @SIsilicon?

**Comment by Lexpartizan** [comment]
We have 2 problems:
1. i dont understand how apply shaders from shadertoy for panorama.
2. Perfomance. God-rays not cheap iterable algoritm on its own. In addition, requires clouds to be known in advance not only at the current point in the texture, but also at those points through which rays are laid in its iterations (about 30 points). At each of these points we will need to calculate the clouds (and this problem number1, i cant apply 2d algoritms for my panorama). That is, clouds, albeit in a slightly simplified form, but will be calculated 30 times.
In another approach, clouds should be calculated in a texture separate from the sky and taken from it. But this will require a few more nodes and a separate viewport, which gives overhead in the form of nodes of godot engine.
3. Godrays produced noise. You can see it in god-rays plugin.

Without godrays on gt 1050 in texture 4k i have 25 fps (50 for 2d).
So, perfomance very important. Default 1k texture for sky.

**Comment by SIsilicon** [comment]
1. My implementation was inspired from various sources but shadertoy.
2. I was actually able to integrate clouds with Godrays before. The clouds were rendered to a buffer, and the alpha value was used to effect the postproccesing effect. I guess it was possible 'cause the clouds themselves were also rendered in screen space.
3. If you play around with values enough, and use the effect subtly, the noise and/or banding effects can be minimized. I might eventually have an option to downsample the effect for performance, but I would need a way to access the depth buffer.

**Comment by SIsilicon** [comment]
How about this? I've made a fork of your project and I'm now working on a way to make our plugins compatible with each other.

**Comment by Lexpartizan** [comment]
And the clouds must also have a space screen in order to work with your plugin. I do not know how to do that.

In general, I thought of using clouds as an occluder and spreading the influence of year-raus only on the texture of the sky so that they would not so much shine in the eyes, as in the general case, but would give a beautiful volumetric light through the clouds to the ground.

**Comment by Lexpartizan** [comment]
**I've made a fork of your project and I'm now working on a way to make our plugins compatible with each other.**

Fantastic idea!

**Comment by SIsilicon** [comment]
> And the clouds must also have a space screen in order to work with your plugin. I do not know how to do that.
> 
> In general, I thought of using clouds as an occluder and spreading the influence of year-raus only on the texture of the sky so that they would not so much shine in the eyes, as in the general case, but would give a beautiful volumetric light through the clouds to the ground.

What I'm thinking of doing decomposing the shader a bit i.e. Have the cloud and the sky rendered separately and then combine together. I can then use the cloud texture in my shader.

**Comment by Lexpartizan** [comment]
Yeah, I thought that it has to be done in the case of using godrays.
There should be no problems. Do I do this or do you prefer it yourself?

**Comment by SIsilicon** [comment]
> Yeah, I thought that it has to be done in the case of using godrays.
> There should be no problems. Do I do this or do you prefer it yourself?

Well, I'm already starting. You could check out the pull request I'll make later. I'll let you know if there are any problems. :)

**Comment by Lexpartizan** [comment]
Thanks!

**Comment by SIsilicon** [comment]
Ok! First snag. I managed to separate the cloud from the sky, but I need to know how my plugin will know whether your assets are in the project. It would've been easy if it was a plugin itself, but I'm not telling you how to have your own project installed.

So the question is, how should it be installed into an ordinary project?

**Comment by Lexpartizan** [comment]
Do as you see fit. I'd rather leave this as a simple scene for Godot than as a plugin. But it's better to have a plugin for godot with godrays, than a scene, without it.

**Comment by SIsilicon** [comment]
That's ok. I figured it out anyway. I'm putting the scene in a group of its own.
Simply adding the godrays as a child should do the trick.

**Comment by SIsilicon** [comment]
Woah! Done.
https://github.com/Lexpartizan/Godot_sky_shader/pull/4

**Comment by Lexpartizan** [comment]
Thanks, just check this!

**Comment by SIsilicon** [comment]
Yep. Pull request is here.
https://github.com/Lexpartizan/Godot_sky_shader/pull/4

Also, it was indeed pretty slow to have both the effects on at the same time, but then again I'm using an integrated graphics processor. So having it slow would be inevitable.

**Comment by Lexpartizan** [comment]
Thank you very much! Sorry for delay.
I spent a long time figuring out how to accept a pull request))

**Comment by Lexpartizan** [comment]
So, i have little work on god_rays and just cut off everything where I didn't see any noticeable changes in the picture to increase performance. And generate a dithering texture.
So, if you interesting...

**Comment by SIsilicon** [comment]
You may make a pull request over at my repository for me to review. 👍

**Comment by Lexpartizan** [comment]
I'm ashamed, but I don't know how to use github))
So it will be better if you download them separately.
So you
https://github.com/Lexpartizan/Godot_sky_shader/blob/master/addons/SIsilicon.vfx.godrays/dith_4k.png

and 
https://github.com/Lexpartizan/Godot_sky_shader/blob/master/addons/SIsilicon.vfx.godrays/GodRays.tres

I combined the uv_to_ray() and depth texture () functions. It seemed to me that there were almost identical calculations and I sacrificed accuracy.

and yet, in your script Godrays.gd, the functions set_exposure, set_attenuation, etc are in _process (delta), I moved them to _ready()

**Comment by Lexpartizan** [comment]
Laugh)) I ran 4K for the dough (texture and viewporty to 4K) and you know what? with god_rays 19 frames per second, without 25 frames per second. On both shaders, so my otimization not needed.

**Comment by SIsilicon** [comment]
Ok.

**Comment by Lexpartizan** [comment]
So i set num_steps to 100 by default.))

**Comment by SIsilicon** [comment]
Technically, the default is still on my repository. You can't really keep my plugin on this one. Not because I don't want it in your repository, but because eventually they won't line up with each other. It's best that you just link to my repository. I'll do the same for your project.

**Comment by SIsilicon** [comment]
> the functions set_exposure, set_attenuation, etc, are in _process (delta), I moved them to _ready()

They were in `_ready` the entire time. :/

**Comment by Lexpartizan** [comment]
I link your repository and write instruction for connection tomorrow.
would like you to delete the part that connects from Your side. In my opinion, it would be easier to do this from my stage. I don't want to clutter your code.
Я просто проверю, если в детях такая нода.

**Comment by SIsilicon** [comment]
> Я просто проверю, если в детях такая нода.
> I’ll just check if there is such a node in children.

Alright I gotcha. I'll take my connection part out.

**Comment by Lexpartizan** [comment]
I will record a video of how to connect Your plugin.

**Comment by SIsilicon** [comment]
Hold on. I'm updating my plugin now. Wait until I uploaded the changes to my repository.

**Comment by Lexpartizan** [comment]
Waiting)) Yes, i have to set up the connection.

**Comment by SIsilicon** [comment]
https://github.com/SIsilicon/Godot-God-Rays-Plugin
Ok. It's done. Let me know if there are any conflicts.

**Comment by SIsilicon** [comment]
By the way, what does )) mean?

**Comment by SIsilicon** [comment]
I'll need pictures eventually. :/

**Comment by Lexpartizan** [comment]
All Ok))
![image](https://user-images.githubusercontent.com/48552343/73675221-0edaaa80-46c3-11ea-9582-d066fdd97650.png)

**Comment by Lexpartizan** [comment]
**By the way, what does "))" mean?**
English not my language. That's why I'm so slow to respond))

**Comment by SIsilicon** [comment]
Yeah I noticed. That's why I used Google translate to translate that Russian text of yours.
Да, я заметил. Вот почему я использовал Google Translate для перевода вашего русского текста.
Is that what you're using?

**Comment by SIsilicon** [comment]
> **By the way, what does "))" mean?**
> English not my language. That's why I'm so slow to respond))

Так это "..."?

**Comment by Lexpartizan** [comment]
Yes, google translate))

i noticed in _process(delta)

material.set_shader_param("num_samples", ProjectSettings.get_setting("rendering/quality/godrays/sample_number"))
	material.set_shader_param("use_pcf5", ProjectSettings.get_setting("rendering/quality/godrays/use_pcf5"))
	material.set_shader_param("dither", ProjectSettings.get_setting("rendering/quality/godrays/dither_amount"))

**Comment by Lexpartizan** [comment]
**"))"**
smiley face multiplied by two))

**Comment by SIsilicon** [comment]
Oh! Well you forgot a colon. :))

**Comment by Lexpartizan** [comment]
We save pixels on the colon.

**Comment by Lexpartizan** [comment]
So, can you in GodRays.gd relocate
material.set_shader_param("num_samples", ProjectSettings.get_setting("rendering/quality/godrays/sample_number"))
to _ready() from _process (delta)

**Comment by Lexpartizan** [comment]
I googled some emoticons a bit and it seems like")) " only I think it's a smiley face. :- ( And I've been writing this for 15 years... I've seen it from others, too. Looks like it was a local meme...

**Comment by Lexpartizan** [comment]
you have broken my delusion, which is almost twenty years old.

**Comment by SIsilicon** [comment]
> So, can you in GodRays.gd relocate
> material.set_shader_param("num_samples", ProjectSettings.get_setting("rendering/quality/godrays/sample_number"))
> to _ready() from _process (delta)

If I do that then setting the value from project won't update in the editor.

**Comment by Lexpartizan** [comment]
OK.
